apiVersion: v1
kind: Namespace
metadata:
  name: "hypershift-alpha"

---

apiVersion: crossplane.stakater.io/v1
kind: HyperShiftHostedCluster
metadata:
  name: "alpha"
  namespace: "hypershift-alpha"
spec:
  parameters:
    awsProviderConfigName: stakater-aws
    hostedCluster:
      name: "alpha"
      namespace: "hypershift-alpha"
      baseDomain: "alpha.saap-prod.5p92zozl.kubeapp.cloud"
      parentClusterBaseDomain: "saap-prod.5p92zozl.kubeapp.cloud"
    dns:
      parentZoneId: "Z0139844OF8Q3OENUQXR"
    certificate:
      duration: 2160h0m0s
      renewBefore: 720h0m0s
      clusterIssuer: letsencrypt
    platform:
      kubevirt:
        compute:
          cores: 16
          memory: 32Gi
        rootVolume:
          persistent:
            size: 300Gi
          type: Persistent
      type: KubeVirt
    replicas: 3
