apiVersion: v1
kind: Namespace
metadata:
  name: "hypershift-alpha"

---

apiVersion: crossplane.stakater.io/v1
kind: HyperShiftHostedCluster
metadata:
  name: "alpha"
  namespace: "hypershift-alpha"
spec:
  # Additional configuration using templated values
